# https://circleci.com/developer/orbs/orb/cypress-io/cypress
version: 2.1
orbs:
  # circleci admin must opt in to 3rd party orb usage
  cypress: cypress-io/cypress@1
executors:
  gatsby-build-mem-hog:
    docker:
      - image: 'cypress/base'
    # Requires a paid plan, and is (unfortunately) required to build this Gatsby site in Circle CI
    resource_class: xlarge
workflows:
  build:
    jobs:
      # NB
      # Need to use a build instead of the dev server since the Cypress run step appears
      # to assume that the start command is much faster than the gatsby dev startup process.
      # It's because of the cypress/install step that the resource_class is even necessary;
      # the gatsby build process always exceeds the 4GB of RAM allocated for free accounts
      - cypress/run:
          executor: gatsby-build-mem-hog
          wait-on: "http://localhost:9000"
          working_directory: web
          yarn: true
          build: yarn build
          start: yarn serve
          # Make sure you have CYPRESS_RECORD_KEY defined as an 
          # env var (you can use project environment variables in CircleCI)
          record: true